import { Parrot } from "./Parrot.js";
import { Dog } from "./Dog.js";
import { Snake } from "./Snake.js";
import { Animal } from "./Animal.js";
import { Mammal } from "./Mammal.js";
const parrot = new Parrot("Mike", 2, 40, true, "male", 0.5, false);
parrot.Sing();
parrot.Eat();
parrot.sex_ = "male";
parrot.GiveBirth();
parrot.Move();
parrot.Migrate();
const dog = new Dog("Adam", 2, 40, true, "male");
dog.Eat();
dog.Guard();
dog.Sleep();
dog.GiveBirth();
const snake = new Snake("Adama", 2, 40, true, "female", true, 50);
snake.Coil("rabbit");
snake.Eat();
snake.GiveBirth();
snake.Move();
snake.PoisonEnemy("mouth");
snake.RegulateTemperature();
snake.ShedSkin();
const animals: Animal[] = [];
animals.push(parrot, dog, snake);
console.log(animals);
const mammals: Mammal[] = [];
const dog1 = new Dog("Kyrylo", 2, 40, true, "male");
mammals.push(dog1, dog);
mammals.forEach((mammal) => mammal.GiveBirth());
